### ISSUE TITLE
php version and next version of laravel error

### ISSUE THREAD

**Issue by jimmy-lilly** [imanghafoori1/laravel-nullable#14]
Same but new problem as Issue #10.

PHP 8.3 just released Nov 23, 2023.
Laravel 11 about to be released this coming Feb 6, 2024.

Using laravel-password-history but this dependency breaks it.

**Comment by imanghafoori1** [comment]
I think you can now install it with php 8.3.* and laravel 11.*

**Comment by jimmy-lilly** [comment]
Thank you @imanghafoori1. That did the trick.
