### ISSUE TITLE
issue with laravel 8.1

### ISSUE THREAD

**Issue by metif12** [imanghafoori1/laravel-nullable#8]
composer require imanghafoori/laravel-nullable
Using version ^1.2 for imanghafoori/laravel-nullable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for imanghafoori/laravel-nullable ^1.2 -> satisfiable by imanghafoori/laravel-nullable[1.2.4, v1.2.0, v1.2.1, v1.2.2, v1.2.3].
    - Installation request for laravel/framework (locked at v8.1.0, required as ^8.0) -> satisfiable by laravel/framework[v8.1.0].
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.4, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.1.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.1.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.1.0].
    - Conclusion: install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by imanghafoori1** [comment]
try again.

**Comment by metif12** [comment]
thanks very much for quick solving this.
